# Generated by Django 6.1 on 2026-10-03 20:28

from django.db import migrations, models


def mark_delivered_cod_paid(apps, schema_editor):
    # Cash on delivery is collected on delivery, so delivered COD orders
    # placed before payment tracking existed are already paid.
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(payment_method='cod', status='delivered').update(payment_status='paid')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_finalized',
            field=models.BooleanField(db_default=True, default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_default='pending', default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_order_id',
            field=models.CharField(blank=True, db_default='', db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_refund_id',
            field=models.CharField(blank=True, db_default='', default='', max_length=40),
        ),
        migrations.AddField(
            model_name='order',
            name='razorpay_signature',
            field=models.CharField(blank=True, db_default='', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('razorpay', 'Online (Razorpay)'), ('cod', 'Cash on Delivery')], default='cod', max_length=10),
        ),
        migrations.RunPython(mark_delivered_cod_paid, migrations.RunPython.noop),
    ]
