"""
Django settings for fexo_project project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = the Django backend root (this is its own repo: backend/).
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from backend/.env (see .env.example for the
# full list of variables this project reads).
load_dotenv(BASE_DIR / '.env')

# The frontend is now a standalone Next.js app (a separate repo/checkout)
# that talks to this project purely over the JSON API mounted under
# /api/ — it no longer needs Django to render templates or serve its
# static assets, so there's no more FRONTEND_DIR/templates coupling here.
# Origin(s) allowed to call the API from a browser. Every known frontend
# origin (local dev, the old Vercel URL, prod, staging and the admin app) is always
# included even if the host's CORS_ALLOWED_ORIGINS env var is set to
# something else/incomplete — this is additive on top of the env var, not
# replaced by it, since there's no dashboard access to fix a misconfigured
# env var directly.
CORS_ALLOWED_ORIGINS = list({
    *(
        origin.strip()
        for origin in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',')
        if origin.strip()
    ),
    'http://localhost:3000',
    'https://fexofashionfrontend.vercel.app',
    'https://fexofashion.com',
    'https://www.fexofashion.com',
    'https://staging.fexofashion.com',
    # Admin app (Fexo-admin): local dev and its Vercel deployment.
    'http://localhost:3001',
    'https://fexo-admin.vercel.app',
})

# Base URL of the Next.js frontend — used to build links that point back
# at it (e.g. the password-reset confirmation link sent by email).
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'https://fexofashion.com')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-^*k9i-vknpf9lcz_0r+w-xja1=zew_rd4czs(j0o$%-&c+%bbl',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get('ALLOWED_HOSTS', '').split(',')
    if host.strip()
]

# Comma-separated list of scheme://host origins allowed to submit
# cross-origin POSTs (Django's CSRF check). Required (non-empty) whenever
# the app is served over HTTPS behind a proxy, e.g. https://fexo-backend.onrender.com
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in os.environ.get('CSRF_TRUSTED_ORIGINS', '').split(',')
    if origin.strip()
]

# Render (and most PaaS hosts) terminate TLS at the edge and proxy to this
# container over plain HTTP, setting X-Forwarded-Proto so Django can tell
# the original request was HTTPS. Without this, request.is_secure() is
# always False behind the proxy, breaking secure cookies / SSL redirects.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    # Toggle off via env only if you're intentionally serving plain HTTP
    # (e.g. an internal/staging deploy without a TLS-terminating proxy).
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'True') == 'True'
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
    'storages',

    'core',
    'accounts',
    'products',
    'categories',
    'cart',
    'orders',
    'wishlist',
    'website',
    'dashboard',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fexo_project.urls'

# No pages are server-rendered any more — the storefront (Fexo-Frontend) and
# the admin (Fexo-admin) are both Next.js apps consuming /api/ as JSON. This
# is kept only for DRF's browsable API and Django's built-in error pages.
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart_summary',
                'wishlist.context_processors.wishlist_summary',
                'categories.context_processors.nav_categories',
                'website.context_processors.site_settings',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        # Kept only so /api/ is browsable (and stays logged in) from a
        # browser session while developing — the Next.js app always uses
        # the token, never cookies.
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 12,
    # DRF stringifies Decimal fields by default (JSON has no fixed-point
    # type, and stringifying avoids float rounding surprises) — but the
    # frontend's TS types declare price/subtotal/grand_total/etc. as
    # `number`, so turn that off and take the (here, harmless) float
    # rounding instead of parseFloat()'ing every money field on the way in.
    'COERCE_DECIMAL_TO_STRING': False,
}

WSGI_APPLICATION = 'fexo_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'fexo_db'),
        'USER': os.environ.get('DB_USER', 'fexo_user'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'sslmode': os.environ.get('DB_SSLMODE', 'prefer'),
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# WhiteNoise serves collected static files straight from the Django/gunicorn
# process — no separate nginx/CDN needed inside the container. See
# https://whitenoise.readthedocs.io/
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Media (admin-uploaded product/category/banner images etc.) lives on local
# disk by default — fine for dev, but wrong for hosts like Render whose
# filesystem is ephemeral (this is what backfill_missing_media exists to
# paper over). Set USE_S3=True in .env to switch 'default' storage to S3 so
# uploads made from /admin/ persist and are served straight from the bucket.
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'ap-south-1')
    AWS_S3_SIGNATURE_VERSION = 's3v4'

    # Don't let a re-upload with the same filename silently clobber an
    # existing object — django-storages appends a random suffix instead.
    AWS_S3_FILE_OVERWRITE = False

    # New buckets default to Object Ownership "Bucket owner enforced", which
    # rejects per-object ACLs outright — public read has to come from a
    # bucket policy instead (see the setup notes), so don't send an ACL.
    AWS_DEFAULT_ACL = None

    # Bucket policy (not per-object ACLs) makes objects public, so plain
    # URLs work without a SigV4 querystring — keeps image URLs stable/cacheable.
    AWS_QUERYSTRING_AUTH = False

    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
    }

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'website:home'
LOGOUT_REDIRECT_URL = 'website:home'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
# Prints emails (password reset, etc.) to the console instead of sending
# them — there's no SMTP configured for local dev. (Previously this was
# set via a `MAILERS` dict, which isn't a real Django setting name, so
# console email was silently never active — Django was falling back to
# the SMTP backend and failing to send.)

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
